# Generated by Django 3.2.4 on 2021-06-27 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_settings_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='address',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
