# Generated by Django 3.2.4 on 2021-06-25 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name_plural': 'About'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': "FAQ's"},
        ),
    ]
