# Generated by Django 3.2.4 on 2021-06-25 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_property_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'Properties'},
        ),
        migrations.AlterModelOptions(
            name='propertybook',
            options={'verbose_name_plural': 'Property Bookings'},
        ),
        migrations.AlterModelOptions(
            name='propertyimages',
            options={'verbose_name_plural': 'Property Images'},
        ),
        migrations.AlterModelOptions(
            name='propertyreview',
            options={'verbose_name_plural': 'Property Reviews'},
        ),
        migrations.AddField(
            model_name='property',
            name='description',
            field=models.TextField(default='lorem ipsum', max_length=10000),
            preserve_default=False,
        ),
    ]
